datasource:
  reader: AUTOSCOUTREADER
  urls:
    #- "https://www.autoscout24.com/lst/ferrari/308?&fregfrom=1981&fregto=1985&ustate=N%2CU&size=20&page="
    - "https://www.autoscout24.com/lst/ferrari/monza?atype=C&page="
output:
  #- type: file
  #  format: dsv
  #  delimiter: "####"
  - type: file
    format: json
  - type: kafka
    config:
      bootstrapServers: dory.srvs.cloudkafka.com:9094
      username: dbetpols
      password: 3AUQkXCP5qHyP0IVa1vdc1vG8V2RzXJL
      topic: dbetpols-proba
