datasource:
  autoscout24:
    urls:
      - "https://www.autoscout24.com/lst/ferrari/308?&fregfrom=1981&fregto=1985&ustate=N%2CU&size=20&page="
      - "https://www.autoscout24.com/lst/bmw/z3/bt_convertible?fregfrom=2001&fregto=2001&body=2&sort=price&desc=0&atype=C&ustate=N%2CU&size=20&page="
