mode: once_and_standby
datasource:
  reader: AUTOSCOUTREADER
  urls:
    - "https://szegheomarci.w3spaces.com/chaz3/carads/246dino.html?page="
output:
  - type: file
    format: dsv
    delimiter: "####"