name: Car Ads packages cleanup
run-name: carAds packages cleanup
on: [push]
jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run cleanup
        uses: actions/delete-package-versions@v4
        with:          
          owner: 'github'
          package-name: 'carads'
          package-type: 'container'
          token: ${{ secrets.GITHUB_PAT }}
          min-versions-to-keep: 5
